"""Nova coluna em usuario - senha

Revision ID: 264cfdd3a0c0
Revises: 7c7f2f2dcd59
Create Date: 2025-08-18 19:29:18.536817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264cfdd3a0c0'
down_revision: Union[str, Sequence[str], None] = '7c7f2f2dcd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'senha')
    # ### end Alembic commands ###
