"""Adicionado Relacionamentos

Revision ID: cf9efe83157e
Revises: 264cfdd3a0c0
Create Date: 2025-08-18 19:49:30.672160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9efe83157e'
down_revision: Union[str, Sequence[str], None] = '264cfdd3a0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_usuario', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_produto_id'))

    # ### end Alembic commands ###
